name: SerenityLoans
main: com.nwmogk.bukkit.loans.SerenityLoans
version: 0.0.2

#softdepend: [Vault]

commands:
  credit:
    description: This command allows credit card functionality
    usage: Use '/<command> help' for info.
    permission: serenityloans.credit
    permission-message: You do not have the required credit permissions!
  creditscore:
    description: This command allows for the checking of credit scores.
    usage: /<command> [player]
    permission: serenityloans.crcheck
    permission-message: You do not have <permission>!
  crunion:
    description: This command encodes the functionality for credit unions (banks).
    usage: Use '/<command> help' for info.
    permission: serenityloans.crunion
    permission-message: You do not have permission to utilize credit unions!
  loan:
    description: This command allows loan functionality.
    usage: Use '/<command> help' for info.
    permission: serenityloans.loan
    permission-message: You do not have the required loan permissions!
  serenityloans:
    description: This command gives information on the SerenityLoans plugin and configuration.
    usage: Use '/<command> help' for info.
    permission: serenityloans.info
    permission-message: You do not have <permission>!
  trust:
    description: This command implements the player trust system.
    usage: Use '/<command> help' for info.
    permission: serenityloans.trust
    permission-message: You do not have <permission>!
  sl-balance:
    description: This command allows players to check their asset balance.
    usage: /<command>
    permission: serenityloans.balance
    permission-message: You do not have <permission>!
  sl-cash:
    description: This command allows players to check their cash balance.
    usage: /<command>
    permission: serenityloans.balance
    permission-message: You do not have <permission>!
  sl-networth:
    description: This command allows players to check their net worth.
    usage: /<command>
    permission: serenityloans.balance
    permission-message: You do not have <permission>!
  sl-pay:
    description: This command allows players to pay other players.
    usage: /<command> [player] [amount]
    permission: serenityloans.pay
    permission-message: You do not have <permission>!
    
permissions:
  serenityloans.credit:
    description:
    default: true
  serenityloans.credit.lend:
    description:
    default: false
  serenityloans.credit.use:
    description:
    default: true
  serenityloans.crcheck:
    description:
    default: true
  serenityloans.crunion:
    description:
    default: true
  serenityloans.crunion.manager:
    description:
    default: false
  serenityloans.crunion.member:
    description:
    default: true
  serenityloans.loan:
    description:
    default: true
  serenityloans.loan.lend:
    description:
    default: true
  serenityloans.loan.borrow:
    description:
    default: true
  serenityloans.info:
    description:
    default: true
  serenityloans.admin:
    description:
    default: op
  serenityloans.audit:
    description:
    default: op
  serenityloans.trust:
    description:
    default: true
  serenityloans.balance:
    description:
    default: true
  serenityloans.pay:
    description:
    default: true
