package com.nwmogk.bukkit.loans.api;

public enum CreditEventType {
	
	LOANOPEN, LOANCLOSE, PAID_BALANCE, PAID_MINIMUM, MISSED_PAYMENT, INACTIVITY, CREDIT_UTILIZATION, CREDIT_LIMIT, BANKRUPT, LOAN_MODIFY, OVERPAYMENT, FINAL_PAYMENT;
	
}
